-- 1. Add user_id to existing tables for multi-user support
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);

-- 2. Create Plaid Items table to store access tokens
CREATE TABLE IF NOT EXISTS plaid_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  access_token TEXT NOT NULL,
  item_id TEXT NOT NULL,
  institution_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Update Unique constraint for budgets to include user_id
ALTER TABLE budgets DROP CONSTRAINT IF EXISTS budgets_category_month_unique;
ALTER TABLE budgets ADD CONSTRAINT budgets_user_category_month_unique UNIQUE (user_id, category, month);
